variable "instance_type" {}
variable "subnet_ids" {}
variable "name" {}
variable "env" {}
variable "vpc_id" {}
variable "allow_app_cidr" {}
variable "bastian_cidr" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "tags" {}
variable "dns_name" {}
variable "kms_arn" {}
variable "parameters" {}
variable "domain_id" {}